# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/sofa/ClionProject/Continuous-CBS

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/sofa/ClionProject/Continuous-CBS

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/sofa/ClionProject/Continuous-CBS/CMakeFiles /home/sofa/ClionProject/Continuous-CBS/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/sofa/ClionProject/Continuous-CBS/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named CCBS

# Build rule for target.
CCBS: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 CCBS
.PHONY : CCBS

# fast build rule for target.
CCBS/fast:
	$(MAKE) -f CMakeFiles/CCBS.dir/build.make CMakeFiles/CCBS.dir/build
.PHONY : CCBS/fast

cbs.o: cbs.cpp.o

.PHONY : cbs.o

# target to build an object file
cbs.cpp.o:
	$(MAKE) -f CMakeFiles/CCBS.dir/build.make CMakeFiles/CCBS.dir/cbs.cpp.o
.PHONY : cbs.cpp.o

cbs.i: cbs.cpp.i

.PHONY : cbs.i

# target to preprocess a source file
cbs.cpp.i:
	$(MAKE) -f CMakeFiles/CCBS.dir/build.make CMakeFiles/CCBS.dir/cbs.cpp.i
.PHONY : cbs.cpp.i

cbs.s: cbs.cpp.s

.PHONY : cbs.s

# target to generate assembly for a file
cbs.cpp.s:
	$(MAKE) -f CMakeFiles/CCBS.dir/build.make CMakeFiles/CCBS.dir/cbs.cpp.s
.PHONY : cbs.cpp.s

config.o: config.cpp.o

.PHONY : config.o

# target to build an object file
config.cpp.o:
	$(MAKE) -f CMakeFiles/CCBS.dir/build.make CMakeFiles/CCBS.dir/config.cpp.o
.PHONY : config.cpp.o

config.i: config.cpp.i

.PHONY : config.i

# target to preprocess a source file
config.cpp.i:
	$(MAKE) -f CMakeFiles/CCBS.dir/build.make CMakeFiles/CCBS.dir/config.cpp.i
.PHONY : config.cpp.i

config.s: config.cpp.s

.PHONY : config.s

# target to generate assembly for a file
config.cpp.s:
	$(MAKE) -f CMakeFiles/CCBS.dir/build.make CMakeFiles/CCBS.dir/config.cpp.s
.PHONY : config.cpp.s

heuristic.o: heuristic.cpp.o

.PHONY : heuristic.o

# target to build an object file
heuristic.cpp.o:
	$(MAKE) -f CMakeFiles/CCBS.dir/build.make CMakeFiles/CCBS.dir/heuristic.cpp.o
.PHONY : heuristic.cpp.o

heuristic.i: heuristic.cpp.i

.PHONY : heuristic.i

# target to preprocess a source file
heuristic.cpp.i:
	$(MAKE) -f CMakeFiles/CCBS.dir/build.make CMakeFiles/CCBS.dir/heuristic.cpp.i
.PHONY : heuristic.cpp.i

heuristic.s: heuristic.cpp.s

.PHONY : heuristic.s

# target to generate assembly for a file
heuristic.cpp.s:
	$(MAKE) -f CMakeFiles/CCBS.dir/build.make CMakeFiles/CCBS.dir/heuristic.cpp.s
.PHONY : heuristic.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/CCBS.dir/build.make CMakeFiles/CCBS.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/CCBS.dir/build.make CMakeFiles/CCBS.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/CCBS.dir/build.make CMakeFiles/CCBS.dir/main.cpp.s
.PHONY : main.cpp.s

map.o: map.cpp.o

.PHONY : map.o

# target to build an object file
map.cpp.o:
	$(MAKE) -f CMakeFiles/CCBS.dir/build.make CMakeFiles/CCBS.dir/map.cpp.o
.PHONY : map.cpp.o

map.i: map.cpp.i

.PHONY : map.i

# target to preprocess a source file
map.cpp.i:
	$(MAKE) -f CMakeFiles/CCBS.dir/build.make CMakeFiles/CCBS.dir/map.cpp.i
.PHONY : map.cpp.i

map.s: map.cpp.s

.PHONY : map.s

# target to generate assembly for a file
map.cpp.s:
	$(MAKE) -f CMakeFiles/CCBS.dir/build.make CMakeFiles/CCBS.dir/map.cpp.s
.PHONY : map.cpp.s

simplex/columnset.o: simplex/columnset.cpp.o

.PHONY : simplex/columnset.o

# target to build an object file
simplex/columnset.cpp.o:
	$(MAKE) -f CMakeFiles/CCBS.dir/build.make CMakeFiles/CCBS.dir/simplex/columnset.cpp.o
.PHONY : simplex/columnset.cpp.o

simplex/columnset.i: simplex/columnset.cpp.i

.PHONY : simplex/columnset.i

# target to preprocess a source file
simplex/columnset.cpp.i:
	$(MAKE) -f CMakeFiles/CCBS.dir/build.make CMakeFiles/CCBS.dir/simplex/columnset.cpp.i
.PHONY : simplex/columnset.cpp.i

simplex/columnset.s: simplex/columnset.cpp.s

.PHONY : simplex/columnset.s

# target to generate assembly for a file
simplex/columnset.cpp.s:
	$(MAKE) -f CMakeFiles/CCBS.dir/build.make CMakeFiles/CCBS.dir/simplex/columnset.cpp.s
.PHONY : simplex/columnset.cpp.s

simplex/constraint.o: simplex/constraint.cpp.o

.PHONY : simplex/constraint.o

# target to build an object file
simplex/constraint.cpp.o:
	$(MAKE) -f CMakeFiles/CCBS.dir/build.make CMakeFiles/CCBS.dir/simplex/constraint.cpp.o
.PHONY : simplex/constraint.cpp.o

simplex/constraint.i: simplex/constraint.cpp.i

.PHONY : simplex/constraint.i

# target to preprocess a source file
simplex/constraint.cpp.i:
	$(MAKE) -f CMakeFiles/CCBS.dir/build.make CMakeFiles/CCBS.dir/simplex/constraint.cpp.i
.PHONY : simplex/constraint.cpp.i

simplex/constraint.s: simplex/constraint.cpp.s

.PHONY : simplex/constraint.s

# target to generate assembly for a file
simplex/constraint.cpp.s:
	$(MAKE) -f CMakeFiles/CCBS.dir/build.make CMakeFiles/CCBS.dir/simplex/constraint.cpp.s
.PHONY : simplex/constraint.cpp.s

simplex/matrix.o: simplex/matrix.cpp.o

.PHONY : simplex/matrix.o

# target to build an object file
simplex/matrix.cpp.o:
	$(MAKE) -f CMakeFiles/CCBS.dir/build.make CMakeFiles/CCBS.dir/simplex/matrix.cpp.o
.PHONY : simplex/matrix.cpp.o

simplex/matrix.i: simplex/matrix.cpp.i

.PHONY : simplex/matrix.i

# target to preprocess a source file
simplex/matrix.cpp.i:
	$(MAKE) -f CMakeFiles/CCBS.dir/build.make CMakeFiles/CCBS.dir/simplex/matrix.cpp.i
.PHONY : simplex/matrix.cpp.i

simplex/matrix.s: simplex/matrix.cpp.s

.PHONY : simplex/matrix.s

# target to generate assembly for a file
simplex/matrix.cpp.s:
	$(MAKE) -f CMakeFiles/CCBS.dir/build.make CMakeFiles/CCBS.dir/simplex/matrix.cpp.s
.PHONY : simplex/matrix.cpp.s

simplex/objectivefunction.o: simplex/objectivefunction.cpp.o

.PHONY : simplex/objectivefunction.o

# target to build an object file
simplex/objectivefunction.cpp.o:
	$(MAKE) -f CMakeFiles/CCBS.dir/build.make CMakeFiles/CCBS.dir/simplex/objectivefunction.cpp.o
.PHONY : simplex/objectivefunction.cpp.o

simplex/objectivefunction.i: simplex/objectivefunction.cpp.i

.PHONY : simplex/objectivefunction.i

# target to preprocess a source file
simplex/objectivefunction.cpp.i:
	$(MAKE) -f CMakeFiles/CCBS.dir/build.make CMakeFiles/CCBS.dir/simplex/objectivefunction.cpp.i
.PHONY : simplex/objectivefunction.cpp.i

simplex/objectivefunction.s: simplex/objectivefunction.cpp.s

.PHONY : simplex/objectivefunction.s

# target to generate assembly for a file
simplex/objectivefunction.cpp.s:
	$(MAKE) -f CMakeFiles/CCBS.dir/build.make CMakeFiles/CCBS.dir/simplex/objectivefunction.cpp.s
.PHONY : simplex/objectivefunction.cpp.s

simplex/simplex.o: simplex/simplex.cpp.o

.PHONY : simplex/simplex.o

# target to build an object file
simplex/simplex.cpp.o:
	$(MAKE) -f CMakeFiles/CCBS.dir/build.make CMakeFiles/CCBS.dir/simplex/simplex.cpp.o
.PHONY : simplex/simplex.cpp.o

simplex/simplex.i: simplex/simplex.cpp.i

.PHONY : simplex/simplex.i

# target to preprocess a source file
simplex/simplex.cpp.i:
	$(MAKE) -f CMakeFiles/CCBS.dir/build.make CMakeFiles/CCBS.dir/simplex/simplex.cpp.i
.PHONY : simplex/simplex.cpp.i

simplex/simplex.s: simplex/simplex.cpp.s

.PHONY : simplex/simplex.s

# target to generate assembly for a file
simplex/simplex.cpp.s:
	$(MAKE) -f CMakeFiles/CCBS.dir/build.make CMakeFiles/CCBS.dir/simplex/simplex.cpp.s
.PHONY : simplex/simplex.cpp.s

simplex/variable.o: simplex/variable.cpp.o

.PHONY : simplex/variable.o

# target to build an object file
simplex/variable.cpp.o:
	$(MAKE) -f CMakeFiles/CCBS.dir/build.make CMakeFiles/CCBS.dir/simplex/variable.cpp.o
.PHONY : simplex/variable.cpp.o

simplex/variable.i: simplex/variable.cpp.i

.PHONY : simplex/variable.i

# target to preprocess a source file
simplex/variable.cpp.i:
	$(MAKE) -f CMakeFiles/CCBS.dir/build.make CMakeFiles/CCBS.dir/simplex/variable.cpp.i
.PHONY : simplex/variable.cpp.i

simplex/variable.s: simplex/variable.cpp.s

.PHONY : simplex/variable.s

# target to generate assembly for a file
simplex/variable.cpp.s:
	$(MAKE) -f CMakeFiles/CCBS.dir/build.make CMakeFiles/CCBS.dir/simplex/variable.cpp.s
.PHONY : simplex/variable.cpp.s

sipp.o: sipp.cpp.o

.PHONY : sipp.o

# target to build an object file
sipp.cpp.o:
	$(MAKE) -f CMakeFiles/CCBS.dir/build.make CMakeFiles/CCBS.dir/sipp.cpp.o
.PHONY : sipp.cpp.o

sipp.i: sipp.cpp.i

.PHONY : sipp.i

# target to preprocess a source file
sipp.cpp.i:
	$(MAKE) -f CMakeFiles/CCBS.dir/build.make CMakeFiles/CCBS.dir/sipp.cpp.i
.PHONY : sipp.cpp.i

sipp.s: sipp.cpp.s

.PHONY : sipp.s

# target to generate assembly for a file
sipp.cpp.s:
	$(MAKE) -f CMakeFiles/CCBS.dir/build.make CMakeFiles/CCBS.dir/sipp.cpp.s
.PHONY : sipp.cpp.s

task.o: task.cpp.o

.PHONY : task.o

# target to build an object file
task.cpp.o:
	$(MAKE) -f CMakeFiles/CCBS.dir/build.make CMakeFiles/CCBS.dir/task.cpp.o
.PHONY : task.cpp.o

task.i: task.cpp.i

.PHONY : task.i

# target to preprocess a source file
task.cpp.i:
	$(MAKE) -f CMakeFiles/CCBS.dir/build.make CMakeFiles/CCBS.dir/task.cpp.i
.PHONY : task.cpp.i

task.s: task.cpp.s

.PHONY : task.s

# target to generate assembly for a file
task.cpp.s:
	$(MAKE) -f CMakeFiles/CCBS.dir/build.make CMakeFiles/CCBS.dir/task.cpp.s
.PHONY : task.cpp.s

tinyxml2.o: tinyxml2.cpp.o

.PHONY : tinyxml2.o

# target to build an object file
tinyxml2.cpp.o:
	$(MAKE) -f CMakeFiles/CCBS.dir/build.make CMakeFiles/CCBS.dir/tinyxml2.cpp.o
.PHONY : tinyxml2.cpp.o

tinyxml2.i: tinyxml2.cpp.i

.PHONY : tinyxml2.i

# target to preprocess a source file
tinyxml2.cpp.i:
	$(MAKE) -f CMakeFiles/CCBS.dir/build.make CMakeFiles/CCBS.dir/tinyxml2.cpp.i
.PHONY : tinyxml2.cpp.i

tinyxml2.s: tinyxml2.cpp.s

.PHONY : tinyxml2.s

# target to generate assembly for a file
tinyxml2.cpp.s:
	$(MAKE) -f CMakeFiles/CCBS.dir/build.make CMakeFiles/CCBS.dir/tinyxml2.cpp.s
.PHONY : tinyxml2.cpp.s

xml_logger.o: xml_logger.cpp.o

.PHONY : xml_logger.o

# target to build an object file
xml_logger.cpp.o:
	$(MAKE) -f CMakeFiles/CCBS.dir/build.make CMakeFiles/CCBS.dir/xml_logger.cpp.o
.PHONY : xml_logger.cpp.o

xml_logger.i: xml_logger.cpp.i

.PHONY : xml_logger.i

# target to preprocess a source file
xml_logger.cpp.i:
	$(MAKE) -f CMakeFiles/CCBS.dir/build.make CMakeFiles/CCBS.dir/xml_logger.cpp.i
.PHONY : xml_logger.cpp.i

xml_logger.s: xml_logger.cpp.s

.PHONY : xml_logger.s

# target to generate assembly for a file
xml_logger.cpp.s:
	$(MAKE) -f CMakeFiles/CCBS.dir/build.make CMakeFiles/CCBS.dir/xml_logger.cpp.s
.PHONY : xml_logger.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... CCBS"
	@echo "... edit_cache"
	@echo "... cbs.o"
	@echo "... cbs.i"
	@echo "... cbs.s"
	@echo "... config.o"
	@echo "... config.i"
	@echo "... config.s"
	@echo "... heuristic.o"
	@echo "... heuristic.i"
	@echo "... heuristic.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... map.o"
	@echo "... map.i"
	@echo "... map.s"
	@echo "... simplex/columnset.o"
	@echo "... simplex/columnset.i"
	@echo "... simplex/columnset.s"
	@echo "... simplex/constraint.o"
	@echo "... simplex/constraint.i"
	@echo "... simplex/constraint.s"
	@echo "... simplex/matrix.o"
	@echo "... simplex/matrix.i"
	@echo "... simplex/matrix.s"
	@echo "... simplex/objectivefunction.o"
	@echo "... simplex/objectivefunction.i"
	@echo "... simplex/objectivefunction.s"
	@echo "... simplex/simplex.o"
	@echo "... simplex/simplex.i"
	@echo "... simplex/simplex.s"
	@echo "... simplex/variable.o"
	@echo "... simplex/variable.i"
	@echo "... simplex/variable.s"
	@echo "... sipp.o"
	@echo "... sipp.i"
	@echo "... sipp.s"
	@echo "... task.o"
	@echo "... task.i"
	@echo "... task.s"
	@echo "... tinyxml2.o"
	@echo "... tinyxml2.i"
	@echo "... tinyxml2.s"
	@echo "... xml_logger.o"
	@echo "... xml_logger.i"
	@echo "... xml_logger.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

